from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from web_tester.storage.session import TestSession


class Reporter:
    """Generates report.json and report.md from a completed TestSession."""

    def __init__(self, session: TestSession) -> None:
        self.session = session

    def generate(
        self,
        status: str,
        final_message: str,
        url: str,
        instructions: str,
        model_provider: str,
        model_name: str,
    ) -> None:
        data = self._build_data(status, final_message, url, instructions, model_provider, model_name)
        self._write_json(data)
        self._write_markdown(data)

    # ------------------------------------------------------------------

    def _build_data(self, status, final_message, url, instructions, provider, model) -> dict:
        steps_data = []
        for s in self.session.steps:
            steps_data.append({
                "step": s.step,
                "timestamp": s.timestamp,
                "tool": s.tool_name,
                "args": s.tool_args,
                "success": s.result_success,
                "message": s.result_message,
                "screenshot": s.screenshot_path,
                "url": s.url_at_step,
                "model_output": s.model_output,
            })

        return {
            "test_name": self.session.root_dir.name,
            "start_time": self.session.start_time.isoformat(),
            "end_time": datetime.now().isoformat(),
            "duration_seconds": round(self.session.duration_seconds, 2),
            "status": status,
            "final_message": final_message,
            "starting_url": url,
            "instructions": instructions,
            "model_provider": provider,
            "model_name": model,
            "total_steps": len(self.session.steps),
            "steps": steps_data,
            "session_dir": str(self.session.root_dir),
        }

    def _write_json(self, data: dict) -> None:
        with open(self.session.report_json, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def _write_markdown(self, data: dict) -> None:
        status_icon = "PASS" if data["status"] == "pass" else "FAIL"
        duration = data["duration_seconds"]
        minutes, seconds = divmod(int(duration), 60)

        lines = [
            f"# Test Report: {data['test_name']}",
            "",
            f"**Status**: {status_icon}  ",
            f"**Date**: {data['start_time'][:19].replace('T', ' ')}  ",
            f"**Duration**: {minutes}m {seconds}s  ",
            f"**Model**: {data['model_provider']} / {data['model_name']}  ",
            f"**Steps**: {data['total_steps']}  ",
            "",
            "## Instructions",
            "",
            data["instructions"],
            "",
            "## Result",
            "",
            data["final_message"],
            "",
            "## Steps",
            "",
        ]

        for step in data["steps"]:
            lines += [
                f"### Step {step['step']} — `{step['tool']}`",
                "",
                f"- **Args**: `{json.dumps(step['args'])}`",
                f"- **Result**: {'✓' if step['success'] else '✗'} {step['message']}",
                f"- **URL**: {step['url']}",
            ]
            if step["screenshot"]:
                rel = Path(step["screenshot"]).name
                lines.append(f"- **Screenshot**: ![step {step['step']}](screenshots/{rel})")
            if step["model_output"]:
                lines += ["", f"> {step['model_output'][:300]}"]
            lines.append("")

        lines += [
            "---",
            "",
            f"*Generated by web-tester on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        ]

        with open(self.session.report_md, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
